"""Remove resumes table and add original_filename

Revision ID: 6fab11a83d6a
Revises: 2adce0411cae
Create Date: 2025-10-23 13:41:22.234111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fab11a83d6a'
down_revision: Union[str, Sequence[str], None] = '2adce0411cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint('resume_analyses_resume_id_fkey', 'resume_analyses', type_='foreignkey')
    
    op.drop_column('resume_analyses', 'resume_id')
    
    op.add_column('resume_analyses', sa.Column('original_filename', sa.String(length=255), nullable=False))
    
    op.create_index(op.f('ix_resume_analyses_user_id'), 'resume_analyses', ['user_id'], unique=False)
    
    op.drop_table('resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Recriar a tabela resumes
    op.create_table('resumes',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='resumes_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    
    # Remover o índice
    op.drop_index(op.f('ix_resume_analyses_user_id'), table_name='resume_analyses')
    
    # Remover a coluna original_filename
    op.drop_column('resume_analyses', 'original_filename')
    
    # Adicionar a coluna resume_id de volta
    op.add_column('resume_analyses', sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False))
    
    # Recriar a foreign key constraint
    op.create_foreign_key('resume_analyses_resume_id_fkey', 'resume_analyses', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###