"""add_status_and_updated_at_to_development_trails

Revision ID: 2217ccac7fb7
Revises: f6ebbb6149e4
Create Date: 2025-12-02 17:22:35.927921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2217ccac7fb7'
down_revision: Union[str, Sequence[str], None] = 'f6ebbb6149e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('development_trails', sa.Column('status', sa.String(length=20), nullable=False, server_default='In Progress'))
    op.add_column('development_trails', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')))
    op.create_index(op.f('ix_development_trails_status'), 'development_trails', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_development_trails_status'), table_name='development_trails')
    op.drop_column('development_trails', 'updated_at')
    op.drop_column('development_trails', 'status')
    # ### end Alembic commands ###