# Generated by Django 4.2.16 on 2026-04-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(blank=True, default='Nova conversa', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('system', 'Sistema')], max_length=10)),
                ('content', models.TextField(max_length=5000)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('previous_consultation', models.BooleanField(default=False, verbose_name='Já fez consulta prévia com nutricionista?')),
                ('alcohol_intake', models.BooleanField(default=False, verbose_name='Ingestão de Álcool')),
                ('smoking', models.BooleanField(default=False, verbose_name='Fumo')),
                ('previous_consultation_objective', models.TextField(blank=True, null=True, verbose_name='Qual era o objetivo na época?')),
                ('previous_consultation_result', models.TextField(blank=True, null=True, verbose_name='Obteve resultado? Se sim, qual?')),
                ('disease_history', models.TextField(blank=True, null=True, verbose_name='Histórico de doenças? Se sim, quais?')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='Faz uso de algum medicamento? Se sim, qual?')),
                ('favorite_foods', models.TextField(blank=True, null=True, verbose_name='Alimentos que você gosta de comer e não podem faltar')),
                ('food_aversions', models.TextField(blank=True, null=True, verbose_name='Aversões/Tabus Alimentares/Alimentos que não gosta')),
                ('body_feeling', models.CharField(blank=True, choices=[('muito_satisfeito', 'Muito Satisfeito'), ('satisfeito', 'Satisfeito'), ('indiferente', 'Indiferente'), ('insatisfeito', 'Insatisfeito'), ('muito_insatisfeito', 'Muito Insatisfeito')], max_length=20, null=True, verbose_name='Sentimento sobre o seu corpo e alimentação?')),
                ('eating_style', models.CharField(choices=[('nao', 'Não'), ('vegetariano', 'Vegetariano(a)'), ('vegano', 'Vegano(a)')], default='nao', max_length=20, verbose_name='Vegetariano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anamnese Nutricional',
                'verbose_name_plural': 'Anamneses Nutricionais',
            },
        ),
    ]
