# Generated by Django 4.2.16 on 2026-04-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='disease_history',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Histórico de doenças? Se sim, quais?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='favorite_foods',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Alimentos que você gosta de comer e não podem faltar'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='food_aversions',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Aversões/Tabus Alimentares/Alimentos que não gosta'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='medications',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Faz uso de algum medicamento? Se sim, qual?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='previous_consultation_objective',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Qual era o objetivo na época?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='previous_consultation_result',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Obteve resultado? Se sim, qual?'),
        ),
    ]
