# Generated by Django 4.2.16 on 2026-04-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_anamnese_disease_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='is_disease_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='is_medication_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='is_previous_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='favorite_foods',
            field=models.TextField(default=0, max_length=5000, verbose_name='Alimentos que você gosta de comer e não podem faltar'),
            preserve_default=False,
        ),
    ]
