# Generated by Django 4.2.16 on 2026-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anamnese_is_disease_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='body_feeling',
            field=models.CharField(blank=True, choices=[('very_satisfied', 'Muito Satisfeito'), ('satisfied', 'Satisfeito'), ('indifferent', 'Indiferente'), ('dissatisfied', 'Insatisfeito'), ('very_dissatisfied', 'Muito Insatisfeito')], max_length=20, null=True, verbose_name='Sentimento sobre o seu corpo e alimentação?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='eating_style',
            field=models.CharField(choices=[('not', 'Não'), ('vegetarian', 'Vegetariano(a)'), ('vegan', 'Vegano(a)')], default='not', max_length=20, verbose_name='Estilo de alimentação'),
        ),
    ]
