# Generated by Django 4.2.16 on 2026-04-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_anamnese_body_feeling_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamnese',
            options={'verbose_name': 'Formulário de Anamnese', 'verbose_name_plural': 'Formulários de Anamnese'},
        ),
    ]
