# Generated by Django 4.2.16 on 2026-04-21 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to=settings.AUTH_USER_MODEL),
        ),
    ]
