# Generated by Django 4.2.16 on 2026-04-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_anamnese_created_at_anamnese_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamnese',
            options={},
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='is_disease_history',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='is_medication_use',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='is_previous_consultation',
        ),
    ]
