# Generated by Django 4.2.16 on 2026-05-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_anamnese_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('U', 'Usuário'), ('A', 'Assistente')], max_length=10),
        ),
    ]
