# Generated by Django 4.2.16 on 2026-06-17 12:15

from django.db import migrations, models
import uuid


def normalize_message_roles(apps, schema_editor):
    """Normaliza valores legados de role ('user'/'assistant') para os códigos
    de 1 caractere ('U'/'A') antes de reduzir o max_length do campo."""
    Message = apps.get_model('core', 'Message')
    Message.objects.filter(role__iexact='user').update(role='U')
    Message.objects.filter(role__iexact='assistant').update(role='A')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_anamnese_food_allergies_food_intolerances'),
    ]

    operations = [
        migrations.RunPython(
            normalize_message_roles, migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name='anamnese',
            options={'verbose_name': 'Anamnese', 'verbose_name_plural': 'Anamneses'},
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('U', 'Usuário'), ('A', 'Assistente')], max_length=1),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-created_at'], name='core_chat_user_id_685424_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='core_messag_chat_id_dc8b8e_idx'),
        ),
    ]
