# Generated by Django 4.2.16 on 2026-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_anamnese_options_alter_anamnese_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='verdict',
            field=models.CharField(blank=True, choices=[('SAFE', 'Seguro'), ('LOW_CONCERN', 'Atenção leve'), ('MODERATE_RISK', 'Risco moderado'), ('HIGH_RISK', 'Alto risco'), ('INSUFFICIENT_DATA', 'Dados insuficientes')], max_length=20, null=True),
        ),
    ]
