# Generated by Django 4.2.16 on 2026-06-17 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_message_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('content', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contexto do usuário',
                'verbose_name_plural': 'Contextos dos usuários',
                'db_table': 'core_user_chat_context',
            },
        ),
    ]
