# Generated by Django 4.2.16 on 2026-06-17 23:49

from django.db import migrations, models


def reinterpret_closed_chats(apps, schema_editor):
    """Antes desta mudança, `is_active=False` era usado tanto para soft delete
    quanto para "chat fechado pela anamnese", o que sumia esses chats da lista.
    Reinterpreta os chats inativos existentes como fechados-mas-visíveis
    (is_active=True, is_open=False), recuperando o histórico do usuário."""
    Chat = apps.get_model('core', 'Chat')
    Chat.objects.filter(is_active=False).update(is_active=True, is_open=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usercontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(reinterpret_closed_chats, migrations.RunPython.noop),
    ]
