# Generated by Django 4.2.16 on 2026-06-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chat_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recommends_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
